#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyHaven_Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BabyHavenDatabase")]
	public partial class BabyHavenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertCart(Cart instance);
    partial void UpdateCart(Cart instance);
    partial void DeleteCart(Cart instance);
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    partial void InsertOrder_Item(Order_Item instance);
    partial void UpdateOrder_Item(Order_Item instance);
    partial void DeleteOrder_Item(Order_Item instance);
    partial void InsertOrder_Table(Order_Table instance);
    partial void UpdateOrder_Table(Order_Table instance);
    partial void DeleteOrder_Table(Order_Table instance);
    partial void InsertPayment(Payment instance);
    partial void UpdatePayment(Payment instance);
    partial void DeletePayment(Payment instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertUser_Table(User_Table instance);
    partial void UpdateUser_Table(User_Table instance);
    partial void DeleteUser_Table(User_Table instance);
    partial void InsertHaven(Haven instance);
    partial void UpdateHaven(Haven instance);
    partial void DeleteHaven(Haven instance);
    partial void InsertTask_Table(Task_Table instance);
    partial void UpdateTask_Table(Task_Table instance);
    partial void DeleteTask_Table(Task_Table instance);
    partial void InsertTasksAssign(TasksAssign instance);
    partial void UpdateTasksAssign(TasksAssign instance);
    partial void DeleteTasksAssign(TasksAssign instance);
    #endregion
		
		public BabyHavenDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BabyHavenDatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BabyHavenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyHavenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyHavenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyHavenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Cart> Carts
		{
			get
			{
				return this.GetTable<Cart>();
			}
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		public System.Data.Linq.Table<Order_Item> Order_Items
		{
			get
			{
				return this.GetTable<Order_Item>();
			}
		}
		
		public System.Data.Linq.Table<Order_Table> Order_Tables
		{
			get
			{
				return this.GetTable<Order_Table>();
			}
		}
		
		public System.Data.Linq.Table<Payment> Payments
		{
			get
			{
				return this.GetTable<Payment>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<User_Table> User_Tables
		{
			get
			{
				return this.GetTable<User_Table>();
			}
		}
		
		public System.Data.Linq.Table<Haven> Havens
		{
			get
			{
				return this.GetTable<Haven>();
			}
		}
		
		public System.Data.Linq.Table<Task_Table> Task_Tables
		{
			get
			{
				return this.GetTable<Task_Table>();
			}
		}
		
		public System.Data.Linq.Table<TasksAssign> TasksAssigns
		{
			get
			{
				return this.GetTable<TasksAssign>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _U_Id;
		
		private string _Surname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cart")]
	public partial class Cart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _U_Id;
		
		private int _P_Id;
		
		private int _Cart_Quantity;
		
		private decimal _Cart_Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OnP_IdChanging(int value);
    partial void OnP_IdChanged();
    partial void OnCart_QuantityChanging(int value);
    partial void OnCart_QuantityChanged();
    partial void OnCart_PriceChanging(decimal value);
    partial void OnCart_PriceChanged();
    #endregion
		
		public Cart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int P_Id
		{
			get
			{
				return this._P_Id;
			}
			set
			{
				if ((this._P_Id != value))
				{
					this.OnP_IdChanging(value);
					this.SendPropertyChanging();
					this._P_Id = value;
					this.SendPropertyChanged("P_Id");
					this.OnP_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cart_Quantity", DbType="Int NOT NULL")]
		public int Cart_Quantity
		{
			get
			{
				return this._Cart_Quantity;
			}
			set
			{
				if ((this._Cart_Quantity != value))
				{
					this.OnCart_QuantityChanging(value);
					this.SendPropertyChanging();
					this._Cart_Quantity = value;
					this.SendPropertyChanged("Cart_Quantity");
					this.OnCart_QuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cart_Price", DbType="Money NOT NULL")]
		public decimal Cart_Price
		{
			get
			{
				return this._Cart_Price;
			}
			set
			{
				if ((this._Cart_Price != value))
				{
					this.OnCart_PriceChanging(value);
					this.SendPropertyChanging();
					this._Cart_Price = value;
					this.SendPropertyChanged("Cart_Price");
					this.OnCart_PriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Client")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _U_Id;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Client()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Order_Item")]
	public partial class Order_Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Order_Item_Id;
		
		private int _Quantity;
		
		private int _O_Id;
		
		private int _Product_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrder_Item_IdChanging(int value);
    partial void OnOrder_Item_IdChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnO_IdChanging(int value);
    partial void OnO_IdChanged();
    partial void OnProduct_IdChanging(int value);
    partial void OnProduct_IdChanged();
    #endregion
		
		public Order_Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Item_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Order_Item_Id
		{
			get
			{
				return this._Order_Item_Id;
			}
			set
			{
				if ((this._Order_Item_Id != value))
				{
					this.OnOrder_Item_IdChanging(value);
					this.SendPropertyChanging();
					this._Order_Item_Id = value;
					this.SendPropertyChanged("Order_Item_Id");
					this.OnOrder_Item_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Id", DbType="Int NOT NULL")]
		public int O_Id
		{
			get
			{
				return this._O_Id;
			}
			set
			{
				if ((this._O_Id != value))
				{
					this.OnO_IdChanging(value);
					this.SendPropertyChanging();
					this._O_Id = value;
					this.SendPropertyChanged("O_Id");
					this.OnO_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Id", DbType="Int NOT NULL")]
		public int Product_Id
		{
			get
			{
				return this._Product_Id;
			}
			set
			{
				if ((this._Product_Id != value))
				{
					this.OnProduct_IdChanging(value);
					this.SendPropertyChanging();
					this._Product_Id = value;
					this.SendPropertyChanged("Product_Id");
					this.OnProduct_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Order_Table")]
	public partial class Order_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _O_Id;
		
		private System.DateTime _O_Date;
		
		private decimal _O_Total;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _O_Email;
		
		private string _O_Address;
		
		private string _O_City;
		
		private string _O_ZipCode;
		
		private string _O_Phone_Number;
		
		private int _UserId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnO_IdChanging(int value);
    partial void OnO_IdChanged();
    partial void OnO_DateChanging(System.DateTime value);
    partial void OnO_DateChanged();
    partial void OnO_TotalChanging(decimal value);
    partial void OnO_TotalChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnO_EmailChanging(string value);
    partial void OnO_EmailChanged();
    partial void OnO_AddressChanging(string value);
    partial void OnO_AddressChanged();
    partial void OnO_CityChanging(string value);
    partial void OnO_CityChanged();
    partial void OnO_ZipCodeChanging(string value);
    partial void OnO_ZipCodeChanged();
    partial void OnO_Phone_NumberChanging(string value);
    partial void OnO_Phone_NumberChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    #endregion
		
		public Order_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int O_Id
		{
			get
			{
				return this._O_Id;
			}
			set
			{
				if ((this._O_Id != value))
				{
					this.OnO_IdChanging(value);
					this.SendPropertyChanging();
					this._O_Id = value;
					this.SendPropertyChanged("O_Id");
					this.OnO_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Date", DbType="Date NOT NULL")]
		public System.DateTime O_Date
		{
			get
			{
				return this._O_Date;
			}
			set
			{
				if ((this._O_Date != value))
				{
					this.OnO_DateChanging(value);
					this.SendPropertyChanging();
					this._O_Date = value;
					this.SendPropertyChanged("O_Date");
					this.OnO_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Total", DbType="Money NOT NULL")]
		public decimal O_Total
		{
			get
			{
				return this._O_Total;
			}
			set
			{
				if ((this._O_Total != value))
				{
					this.OnO_TotalChanging(value);
					this.SendPropertyChanging();
					this._O_Total = value;
					this.SendPropertyChanged("O_Total");
					this.OnO_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string O_Email
		{
			get
			{
				return this._O_Email;
			}
			set
			{
				if ((this._O_Email != value))
				{
					this.OnO_EmailChanging(value);
					this.SendPropertyChanging();
					this._O_Email = value;
					this.SendPropertyChanged("O_Email");
					this.OnO_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string O_Address
		{
			get
			{
				return this._O_Address;
			}
			set
			{
				if ((this._O_Address != value))
				{
					this.OnO_AddressChanging(value);
					this.SendPropertyChanging();
					this._O_Address = value;
					this.SendPropertyChanged("O_Address");
					this.OnO_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string O_City
		{
			get
			{
				return this._O_City;
			}
			set
			{
				if ((this._O_City != value))
				{
					this.OnO_CityChanging(value);
					this.SendPropertyChanging();
					this._O_City = value;
					this.SendPropertyChanged("O_City");
					this.OnO_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_ZipCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string O_ZipCode
		{
			get
			{
				return this._O_ZipCode;
			}
			set
			{
				if ((this._O_ZipCode != value))
				{
					this.OnO_ZipCodeChanging(value);
					this.SendPropertyChanging();
					this._O_ZipCode = value;
					this.SendPropertyChanged("O_ZipCode");
					this.OnO_ZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Phone_Number", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string O_Phone_Number
		{
			get
			{
				return this._O_Phone_Number;
			}
			set
			{
				if ((this._O_Phone_Number != value))
				{
					this.OnO_Phone_NumberChanging(value);
					this.SendPropertyChanging();
					this._O_Phone_Number = value;
					this.SendPropertyChanged("O_Phone_Number");
					this.OnO_Phone_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Payment")]
	public partial class Payment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pay_Id;
		
		private int _O_Id;
		
		private string _Card_Num;
		
		private string _CVV;
		
		private string _Expiry_date;
		
		private string _CardHolder_Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPay_IdChanging(int value);
    partial void OnPay_IdChanged();
    partial void OnO_IdChanging(int value);
    partial void OnO_IdChanged();
    partial void OnCard_NumChanging(string value);
    partial void OnCard_NumChanged();
    partial void OnCVVChanging(string value);
    partial void OnCVVChanged();
    partial void OnExpiry_dateChanging(string value);
    partial void OnExpiry_dateChanged();
    partial void OnCardHolder_NameChanging(string value);
    partial void OnCardHolder_NameChanged();
    #endregion
		
		public Payment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Pay_Id
		{
			get
			{
				return this._Pay_Id;
			}
			set
			{
				if ((this._Pay_Id != value))
				{
					this.OnPay_IdChanging(value);
					this.SendPropertyChanging();
					this._Pay_Id = value;
					this.SendPropertyChanged("Pay_Id");
					this.OnPay_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int O_Id
		{
			get
			{
				return this._O_Id;
			}
			set
			{
				if ((this._O_Id != value))
				{
					this.OnO_IdChanging(value);
					this.SendPropertyChanging();
					this._O_Id = value;
					this.SendPropertyChanged("O_Id");
					this.OnO_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card_Num", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Card_Num
		{
			get
			{
				return this._Card_Num;
			}
			set
			{
				if ((this._Card_Num != value))
				{
					this.OnCard_NumChanging(value);
					this.SendPropertyChanging();
					this._Card_Num = value;
					this.SendPropertyChanged("Card_Num");
					this.OnCard_NumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CVV
		{
			get
			{
				return this._CVV;
			}
			set
			{
				if ((this._CVV != value))
				{
					this.OnCVVChanging(value);
					this.SendPropertyChanging();
					this._CVV = value;
					this.SendPropertyChanged("CVV");
					this.OnCVVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expiry_date", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Expiry_date
		{
			get
			{
				return this._Expiry_date;
			}
			set
			{
				if ((this._Expiry_date != value))
				{
					this.OnExpiry_dateChanging(value);
					this.SendPropertyChanging();
					this._Expiry_date = value;
					this.SendPropertyChanged("Expiry_date");
					this.OnExpiry_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolder_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CardHolder_Name
		{
			get
			{
				return this._CardHolder_Name;
			}
			set
			{
				if ((this._CardHolder_Name != value))
				{
					this.OnCardHolder_NameChanging(value);
					this.SendPropertyChanging();
					this._CardHolder_Name = value;
					this.SendPropertyChanged("CardHolder_Name");
					this.OnCardHolder_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Product_Id;
		
		private string _P_Name;
		
		private string _P_Description;
		
		private string _P_Category;
		
		private int _P_Quantity;
		
		private decimal _P_Price;
		
		private System.DateTime _P_DateCreated;
		
		private string _P_Image;
		
		private bool _isActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IdChanging(int value);
    partial void OnProduct_IdChanged();
    partial void OnP_NameChanging(string value);
    partial void OnP_NameChanged();
    partial void OnP_DescriptionChanging(string value);
    partial void OnP_DescriptionChanged();
    partial void OnP_CategoryChanging(string value);
    partial void OnP_CategoryChanged();
    partial void OnP_QuantityChanging(int value);
    partial void OnP_QuantityChanged();
    partial void OnP_PriceChanging(decimal value);
    partial void OnP_PriceChanged();
    partial void OnP_DateCreatedChanging(System.DateTime value);
    partial void OnP_DateCreatedChanged();
    partial void OnP_ImageChanging(string value);
    partial void OnP_ImageChanged();
    partial void OnisActiveChanging(bool value);
    partial void OnisActiveChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Product_Id
		{
			get
			{
				return this._Product_Id;
			}
			set
			{
				if ((this._Product_Id != value))
				{
					this.OnProduct_IdChanging(value);
					this.SendPropertyChanging();
					this._Product_Id = value;
					this.SendPropertyChanged("Product_Id");
					this.OnProduct_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Name
		{
			get
			{
				return this._P_Name;
			}
			set
			{
				if ((this._P_Name != value))
				{
					this.OnP_NameChanging(value);
					this.SendPropertyChanging();
					this._P_Name = value;
					this.SendPropertyChanged("P_Name");
					this.OnP_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string P_Description
		{
			get
			{
				return this._P_Description;
			}
			set
			{
				if ((this._P_Description != value))
				{
					this.OnP_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._P_Description = value;
					this.SendPropertyChanged("P_Description");
					this.OnP_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Category", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Category
		{
			get
			{
				return this._P_Category;
			}
			set
			{
				if ((this._P_Category != value))
				{
					this.OnP_CategoryChanging(value);
					this.SendPropertyChanging();
					this._P_Category = value;
					this.SendPropertyChanged("P_Category");
					this.OnP_CategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Quantity", DbType="Int NOT NULL")]
		public int P_Quantity
		{
			get
			{
				return this._P_Quantity;
			}
			set
			{
				if ((this._P_Quantity != value))
				{
					this.OnP_QuantityChanging(value);
					this.SendPropertyChanging();
					this._P_Quantity = value;
					this.SendPropertyChanged("P_Quantity");
					this.OnP_QuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Price", DbType="Money NOT NULL")]
		public decimal P_Price
		{
			get
			{
				return this._P_Price;
			}
			set
			{
				if ((this._P_Price != value))
				{
					this.OnP_PriceChanging(value);
					this.SendPropertyChanging();
					this._P_Price = value;
					this.SendPropertyChanged("P_Price");
					this.OnP_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_DateCreated", DbType="Date NOT NULL")]
		public System.DateTime P_DateCreated
		{
			get
			{
				return this._P_DateCreated;
			}
			set
			{
				if ((this._P_DateCreated != value))
				{
					this.OnP_DateCreatedChanging(value);
					this.SendPropertyChanging();
					this._P_DateCreated = value;
					this.SendPropertyChanged("P_DateCreated");
					this.OnP_DateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Image", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Image
		{
			get
			{
				return this._P_Image;
			}
			set
			{
				if ((this._P_Image != value))
				{
					this.OnP_ImageChanging(value);
					this.SendPropertyChanging();
					this._P_Image = value;
					this.SendPropertyChanged("P_Image");
					this.OnP_ImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit NOT NULL")]
		public bool isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Table")]
	public partial class User_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Id;
		
		private string _Email;
		
		private string _Password;
		
		private int _UserType;
		
		private string _Name;
		
		private string _Surname;
		
		private string _Phone_Number;
		
		private string _Address;
		
		private System.DateTime _Register_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdChanging(int value);
    partial void OnUser_IdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserTypeChanging(int value);
    partial void OnUserTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnPhone_NumberChanging(string value);
    partial void OnPhone_NumberChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnRegister_DateChanging(System.DateTime value);
    partial void OnRegister_DateChanged();
    #endregion
		
		public User_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="Int NOT NULL")]
		public int UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_Number", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this.OnPhone_NumberChanging(value);
					this.SendPropertyChanging();
					this._Phone_Number = value;
					this.SendPropertyChanged("Phone_Number");
					this.OnPhone_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Register_Date", DbType="Date NOT NULL")]
		public System.DateTime Register_Date
		{
			get
			{
				return this._Register_Date;
			}
			set
			{
				if ((this._Register_Date != value))
				{
					this.OnRegister_DateChanging(value);
					this.SendPropertyChanging();
					this._Register_Date = value;
					this.SendPropertyChanged("Register_Date");
					this.OnRegister_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Haven")]
	public partial class Haven : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _U_Id;
		
		private bool _dealt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OndealtChanging(bool value);
    partial void OndealtChanged();
    #endregion
		
		public Haven()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dealt", DbType="Bit NOT NULL")]
		public bool dealt
		{
			get
			{
				return this._dealt;
			}
			set
			{
				if ((this._dealt != value))
				{
					this.OndealtChanging(value);
					this.SendPropertyChanging();
					this._dealt = value;
					this.SendPropertyChanged("dealt");
					this.OndealtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Task_Table")]
	public partial class Task_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _T_Id;
		
		private string _T_Des;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnT_IdChanging(int value);
    partial void OnT_IdChanged();
    partial void OnT_DesChanging(string value);
    partial void OnT_DesChanged();
    #endregion
		
		public Task_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int T_Id
		{
			get
			{
				return this._T_Id;
			}
			set
			{
				if ((this._T_Id != value))
				{
					this.OnT_IdChanging(value);
					this.SendPropertyChanging();
					this._T_Id = value;
					this.SendPropertyChanged("T_Id");
					this.OnT_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Des", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string T_Des
		{
			get
			{
				return this._T_Des;
			}
			set
			{
				if ((this._T_Des != value))
				{
					this.OnT_DesChanging(value);
					this.SendPropertyChanging();
					this._T_Des = value;
					this.SendPropertyChanged("T_Des");
					this.OnT_DesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TasksAssign")]
	public partial class TasksAssign : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _A_Id;
		
		private int _T_Id;
		
		private int _Admin_Id;
		
		private bool _T_Completed;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnA_IdChanging(int value);
    partial void OnA_IdChanged();
    partial void OnT_IdChanging(int value);
    partial void OnT_IdChanged();
    partial void OnAdmin_IdChanging(int value);
    partial void OnAdmin_IdChanged();
    partial void OnT_CompletedChanging(bool value);
    partial void OnT_CompletedChanged();
    #endregion
		
		public TasksAssign()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int A_Id
		{
			get
			{
				return this._A_Id;
			}
			set
			{
				if ((this._A_Id != value))
				{
					this.OnA_IdChanging(value);
					this.SendPropertyChanging();
					this._A_Id = value;
					this.SendPropertyChanged("A_Id");
					this.OnA_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Id", DbType="Int NOT NULL")]
		public int T_Id
		{
			get
			{
				return this._T_Id;
			}
			set
			{
				if ((this._T_Id != value))
				{
					this.OnT_IdChanging(value);
					this.SendPropertyChanging();
					this._T_Id = value;
					this.SendPropertyChanged("T_Id");
					this.OnT_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Id", DbType="Int NOT NULL")]
		public int Admin_Id
		{
			get
			{
				return this._Admin_Id;
			}
			set
			{
				if ((this._Admin_Id != value))
				{
					this.OnAdmin_IdChanging(value);
					this.SendPropertyChanging();
					this._Admin_Id = value;
					this.SendPropertyChanged("Admin_Id");
					this.OnAdmin_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Completed", DbType="Bit NOT NULL")]
		public bool T_Completed
		{
			get
			{
				return this._T_Completed;
			}
			set
			{
				if ((this._T_Completed != value))
				{
					this.OnT_CompletedChanging(value);
					this.SendPropertyChanging();
					this._T_Completed = value;
					this.SendPropertyChanged("T_Completed");
					this.OnT_CompletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
