<?xml version="1.0" encoding="utf-8"?><Database Name="BabyHavenDatabase" Class="BabyHavenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BabyHavenDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BabyHavenDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="U_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Table_Admin" Member="User_Table" ThisKey="U_Id" OtherKey="User_Id" Type="User_Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="U_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="P_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cart_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cart_Price" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Product_Cart" Member="Product" ThisKey="P_Id" OtherKey="Product_Id" Type="Product" IsForeignKey="true" />
      <Association Name="User_Table_Cart" Member="User_Table" ThisKey="U_Id" OtherKey="User_Id" Type="User_Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="U_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Table_Client" Member="User_Table" ThisKey="U_Id" OtherKey="User_Id" Type="User_Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Custom_Prod" Member="Custom_Prods">
    <Type Name="Custom_Prod">
      <Column Name="CustProd_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustProd_Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="U_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="O_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Table_Custom_Prod" Member="Order_Table" ThisKey="O_Id" OtherKey="O_Id" Type="Order_Table" IsForeignKey="true" />
      <Association Name="User_Table_Custom_Prod" Member="User_Table" ThisKey="U_Id" OtherKey="User_Id" Type="User_Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HackFeedback" Member="HackFeedbacks">
    <Type Name="HackFeedback">
      <Column Name="HF_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="U_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HF_Hack" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_Table_HackFeedback" Member="User_Table" ThisKey="U_Id" OtherKey="User_Id" Type="User_Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Table" Member="Order_Tables">
    <Type Name="Order_Table">
      <Column Name="O_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="O_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="O_Total" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="O_Tax" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="O_Discount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="O_Shipping" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="O_Quantity" Type="System.String" DbType="VARChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Order_Table_Custom_Prod" Member="Custom_Prods" ThisKey="O_Id" OtherKey="O_Id" Type="Custom_Prod" />
      <Association Name="Order_Table_Payment" Member="Payments" ThisKey="O_Id" OtherKey="O_Id" Type="Payment" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="Pay_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="O_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Card_Num" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CVV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Expiry_date" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CardHolder_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Order_Table_Payment" Member="Order_Table" ThisKey="O_Id" OtherKey="O_Id" Type="Order_Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="P_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="P_Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P_Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="P_DateCreated" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="P_Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Product_Cart" Member="Carts" ThisKey="Product_Id" OtherKey="P_Id" Type="Cart" />
    </Type>
  </Table>
  <Table Name="dbo.User_Table" Member="User_Tables">
    <Type Name="User_Table">
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone_Number" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Register_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="User_Table_Admin" Member="Admin" ThisKey="User_Id" OtherKey="U_Id" Type="Admin" Cardinality="One" />
      <Association Name="User_Table_Cart" Member="Carts" ThisKey="User_Id" OtherKey="U_Id" Type="Cart" />
      <Association Name="User_Table_Client" Member="Client" ThisKey="User_Id" OtherKey="U_Id" Type="Client" Cardinality="One" />
      <Association Name="User_Table_Custom_Prod" Member="Custom_Prods" ThisKey="User_Id" OtherKey="U_Id" Type="Custom_Prod" />
      <Association Name="User_Table_HackFeedback" Member="HackFeedbacks" ThisKey="User_Id" OtherKey="U_Id" Type="HackFeedback" />
    </Type>
  </Table>
</Database>