#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyHaven_Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BabyHavenDatabase")]
	public partial class BabyHavenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertCart(Cart instance);
    partial void UpdateCart(Cart instance);
    partial void DeleteCart(Cart instance);
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    partial void InsertCustom_Prod(Custom_Prod instance);
    partial void UpdateCustom_Prod(Custom_Prod instance);
    partial void DeleteCustom_Prod(Custom_Prod instance);
    partial void InsertHackFeedback(HackFeedback instance);
    partial void UpdateHackFeedback(HackFeedback instance);
    partial void DeleteHackFeedback(HackFeedback instance);
    partial void InsertOrder_Table(Order_Table instance);
    partial void UpdateOrder_Table(Order_Table instance);
    partial void DeleteOrder_Table(Order_Table instance);
    partial void InsertPayment(Payment instance);
    partial void UpdatePayment(Payment instance);
    partial void DeletePayment(Payment instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertUser_Table(User_Table instance);
    partial void UpdateUser_Table(User_Table instance);
    partial void DeleteUser_Table(User_Table instance);
    #endregion
		
		public BabyHavenDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BabyHavenDatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BabyHavenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyHavenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyHavenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyHavenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Cart> Carts
		{
			get
			{
				return this.GetTable<Cart>();
			}
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		public System.Data.Linq.Table<Custom_Prod> Custom_Prods
		{
			get
			{
				return this.GetTable<Custom_Prod>();
			}
		}
		
		public System.Data.Linq.Table<HackFeedback> HackFeedbacks
		{
			get
			{
				return this.GetTable<HackFeedback>();
			}
		}
		
		public System.Data.Linq.Table<Order_Table> Order_Tables
		{
			get
			{
				return this.GetTable<Order_Table>();
			}
		}
		
		public System.Data.Linq.Table<Payment> Payments
		{
			get
			{
				return this.GetTable<Payment>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<User_Table> User_Tables
		{
			get
			{
				return this.GetTable<User_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _U_Id;
		
		private string _Surname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cart")]
	public partial class Cart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _U_Id;
		
		private int _P_Id;
		
		private int _Cart_Quantity;
		
		private decimal _Cart_Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OnP_IdChanging(int value);
    partial void OnP_IdChanged();
    partial void OnCart_QuantityChanging(int value);
    partial void OnCart_QuantityChanged();
    partial void OnCart_PriceChanging(decimal value);
    partial void OnCart_PriceChanged();
    #endregion
		
		public Cart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int P_Id
		{
			get
			{
				return this._P_Id;
			}
			set
			{
				if ((this._P_Id != value))
				{
					this.OnP_IdChanging(value);
					this.SendPropertyChanging();
					this._P_Id = value;
					this.SendPropertyChanged("P_Id");
					this.OnP_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cart_Quantity", DbType="Int NOT NULL")]
		public int Cart_Quantity
		{
			get
			{
				return this._Cart_Quantity;
			}
			set
			{
				if ((this._Cart_Quantity != value))
				{
					this.OnCart_QuantityChanging(value);
					this.SendPropertyChanging();
					this._Cart_Quantity = value;
					this.SendPropertyChanged("Cart_Quantity");
					this.OnCart_QuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cart_Price", DbType="Money NOT NULL")]
		public decimal Cart_Price
		{
			get
			{
				return this._Cart_Price;
			}
			set
			{
				if ((this._Cart_Price != value))
				{
					this.OnCart_PriceChanging(value);
					this.SendPropertyChanging();
					this._Cart_Price = value;
					this.SendPropertyChanged("Cart_Price");
					this.OnCart_PriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Client")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _U_Id;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Client()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Custom_Prod")]
	public partial class Custom_Prod : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustProd_Id;
		
		private string _CustProd_Image;
		
		private int _U_Id;
		
		private int _O_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustProd_IdChanging(int value);
    partial void OnCustProd_IdChanged();
    partial void OnCustProd_ImageChanging(string value);
    partial void OnCustProd_ImageChanged();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OnO_IdChanging(int value);
    partial void OnO_IdChanged();
    #endregion
		
		public Custom_Prod()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustProd_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CustProd_Id
		{
			get
			{
				return this._CustProd_Id;
			}
			set
			{
				if ((this._CustProd_Id != value))
				{
					this.OnCustProd_IdChanging(value);
					this.SendPropertyChanging();
					this._CustProd_Id = value;
					this.SendPropertyChanged("CustProd_Id");
					this.OnCustProd_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustProd_Image", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CustProd_Image
		{
			get
			{
				return this._CustProd_Image;
			}
			set
			{
				if ((this._CustProd_Image != value))
				{
					this.OnCustProd_ImageChanging(value);
					this.SendPropertyChanging();
					this._CustProd_Image = value;
					this.SendPropertyChanged("CustProd_Image");
					this.OnCustProd_ImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL")]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Id", DbType="Int NOT NULL")]
		public int O_Id
		{
			get
			{
				return this._O_Id;
			}
			set
			{
				if ((this._O_Id != value))
				{
					this.OnO_IdChanging(value);
					this.SendPropertyChanging();
					this._O_Id = value;
					this.SendPropertyChanged("O_Id");
					this.OnO_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HackFeedback")]
	public partial class HackFeedback : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HF_Id;
		
		private int _U_Id;
		
		private string _HF_Hack;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHF_IdChanging(int value);
    partial void OnHF_IdChanged();
    partial void OnU_IdChanging(int value);
    partial void OnU_IdChanged();
    partial void OnHF_HackChanging(string value);
    partial void OnHF_HackChanged();
    #endregion
		
		public HackFeedback()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HF_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HF_Id
		{
			get
			{
				return this._HF_Id;
			}
			set
			{
				if ((this._HF_Id != value))
				{
					this.OnHF_IdChanging(value);
					this.SendPropertyChanging();
					this._HF_Id = value;
					this.SendPropertyChanged("HF_Id");
					this.OnHF_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int U_Id
		{
			get
			{
				return this._U_Id;
			}
			set
			{
				if ((this._U_Id != value))
				{
					this.OnU_IdChanging(value);
					this.SendPropertyChanging();
					this._U_Id = value;
					this.SendPropertyChanged("U_Id");
					this.OnU_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HF_Hack", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HF_Hack
		{
			get
			{
				return this._HF_Hack;
			}
			set
			{
				if ((this._HF_Hack != value))
				{
					this.OnHF_HackChanging(value);
					this.SendPropertyChanging();
					this._HF_Hack = value;
					this.SendPropertyChanged("HF_Hack");
					this.OnHF_HackChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Order_Table")]
	public partial class Order_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _O_Id;
		
		private System.DateTime _O_Date;
		
		private decimal _O_Total;
		
		private decimal _O_Tax;
		
		private decimal _O_Discount;
		
		private decimal _O_Shipping;
		
		private string _O_Quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnO_IdChanging(int value);
    partial void OnO_IdChanged();
    partial void OnO_DateChanging(System.DateTime value);
    partial void OnO_DateChanged();
    partial void OnO_TotalChanging(decimal value);
    partial void OnO_TotalChanged();
    partial void OnO_TaxChanging(decimal value);
    partial void OnO_TaxChanged();
    partial void OnO_DiscountChanging(decimal value);
    partial void OnO_DiscountChanged();
    partial void OnO_ShippingChanging(decimal value);
    partial void OnO_ShippingChanged();
    partial void OnO_QuantityChanging(string value);
    partial void OnO_QuantityChanged();
    #endregion
		
		public Order_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int O_Id
		{
			get
			{
				return this._O_Id;
			}
			set
			{
				if ((this._O_Id != value))
				{
					this.OnO_IdChanging(value);
					this.SendPropertyChanging();
					this._O_Id = value;
					this.SendPropertyChanged("O_Id");
					this.OnO_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Date", DbType="Date NOT NULL")]
		public System.DateTime O_Date
		{
			get
			{
				return this._O_Date;
			}
			set
			{
				if ((this._O_Date != value))
				{
					this.OnO_DateChanging(value);
					this.SendPropertyChanging();
					this._O_Date = value;
					this.SendPropertyChanged("O_Date");
					this.OnO_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Total", DbType="Money NOT NULL")]
		public decimal O_Total
		{
			get
			{
				return this._O_Total;
			}
			set
			{
				if ((this._O_Total != value))
				{
					this.OnO_TotalChanging(value);
					this.SendPropertyChanging();
					this._O_Total = value;
					this.SendPropertyChanged("O_Total");
					this.OnO_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Tax", DbType="Money NOT NULL")]
		public decimal O_Tax
		{
			get
			{
				return this._O_Tax;
			}
			set
			{
				if ((this._O_Tax != value))
				{
					this.OnO_TaxChanging(value);
					this.SendPropertyChanging();
					this._O_Tax = value;
					this.SendPropertyChanged("O_Tax");
					this.OnO_TaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Discount", DbType="Money NOT NULL")]
		public decimal O_Discount
		{
			get
			{
				return this._O_Discount;
			}
			set
			{
				if ((this._O_Discount != value))
				{
					this.OnO_DiscountChanging(value);
					this.SendPropertyChanging();
					this._O_Discount = value;
					this.SendPropertyChanged("O_Discount");
					this.OnO_DiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Shipping", DbType="Money NOT NULL")]
		public decimal O_Shipping
		{
			get
			{
				return this._O_Shipping;
			}
			set
			{
				if ((this._O_Shipping != value))
				{
					this.OnO_ShippingChanging(value);
					this.SendPropertyChanging();
					this._O_Shipping = value;
					this.SendPropertyChanged("O_Shipping");
					this.OnO_ShippingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Quantity", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string O_Quantity
		{
			get
			{
				return this._O_Quantity;
			}
			set
			{
				if ((this._O_Quantity != value))
				{
					this.OnO_QuantityChanging(value);
					this.SendPropertyChanging();
					this._O_Quantity = value;
					this.SendPropertyChanged("O_Quantity");
					this.OnO_QuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Payment")]
	public partial class Payment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pay_Id;
		
		private int _O_Id;
		
		private string _Card_Num;
		
		private string _CVV;
		
		private string _Expiry_date;
		
		private string _CardHolder_Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPay_IdChanging(int value);
    partial void OnPay_IdChanged();
    partial void OnO_IdChanging(int value);
    partial void OnO_IdChanged();
    partial void OnCard_NumChanging(string value);
    partial void OnCard_NumChanged();
    partial void OnCVVChanging(string value);
    partial void OnCVVChanged();
    partial void OnExpiry_dateChanging(string value);
    partial void OnExpiry_dateChanged();
    partial void OnCardHolder_NameChanging(string value);
    partial void OnCardHolder_NameChanged();
    #endregion
		
		public Payment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Pay_Id
		{
			get
			{
				return this._Pay_Id;
			}
			set
			{
				if ((this._Pay_Id != value))
				{
					this.OnPay_IdChanging(value);
					this.SendPropertyChanging();
					this._Pay_Id = value;
					this.SendPropertyChanged("Pay_Id");
					this.OnPay_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int O_Id
		{
			get
			{
				return this._O_Id;
			}
			set
			{
				if ((this._O_Id != value))
				{
					this.OnO_IdChanging(value);
					this.SendPropertyChanging();
					this._O_Id = value;
					this.SendPropertyChanged("O_Id");
					this.OnO_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card_Num", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Card_Num
		{
			get
			{
				return this._Card_Num;
			}
			set
			{
				if ((this._Card_Num != value))
				{
					this.OnCard_NumChanging(value);
					this.SendPropertyChanging();
					this._Card_Num = value;
					this.SendPropertyChanged("Card_Num");
					this.OnCard_NumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CVV
		{
			get
			{
				return this._CVV;
			}
			set
			{
				if ((this._CVV != value))
				{
					this.OnCVVChanging(value);
					this.SendPropertyChanging();
					this._CVV = value;
					this.SendPropertyChanged("CVV");
					this.OnCVVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expiry_date", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Expiry_date
		{
			get
			{
				return this._Expiry_date;
			}
			set
			{
				if ((this._Expiry_date != value))
				{
					this.OnExpiry_dateChanging(value);
					this.SendPropertyChanging();
					this._Expiry_date = value;
					this.SendPropertyChanged("Expiry_date");
					this.OnExpiry_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolder_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CardHolder_Name
		{
			get
			{
				return this._CardHolder_Name;
			}
			set
			{
				if ((this._CardHolder_Name != value))
				{
					this.OnCardHolder_NameChanging(value);
					this.SendPropertyChanging();
					this._CardHolder_Name = value;
					this.SendPropertyChanged("CardHolder_Name");
					this.OnCardHolder_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Product_Id;
		
		private string _P_Name;
		
		private string _P_Description;
		
		private string _P_Category;
		
		private int _P_Quantity;
		
		private decimal _P_Price;
		
		private System.DateTime _P_DateCreated;
		
		private string _P_Image;
		
		private bool _isActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IdChanging(int value);
    partial void OnProduct_IdChanged();
    partial void OnP_NameChanging(string value);
    partial void OnP_NameChanged();
    partial void OnP_DescriptionChanging(string value);
    partial void OnP_DescriptionChanged();
    partial void OnP_CategoryChanging(string value);
    partial void OnP_CategoryChanged();
    partial void OnP_QuantityChanging(int value);
    partial void OnP_QuantityChanged();
    partial void OnP_PriceChanging(decimal value);
    partial void OnP_PriceChanged();
    partial void OnP_DateCreatedChanging(System.DateTime value);
    partial void OnP_DateCreatedChanged();
    partial void OnP_ImageChanging(string value);
    partial void OnP_ImageChanged();
    partial void OnisActiveChanging(bool value);
    partial void OnisActiveChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Product_Id
		{
			get
			{
				return this._Product_Id;
			}
			set
			{
				if ((this._Product_Id != value))
				{
					this.OnProduct_IdChanging(value);
					this.SendPropertyChanging();
					this._Product_Id = value;
					this.SendPropertyChanged("Product_Id");
					this.OnProduct_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Name
		{
			get
			{
				return this._P_Name;
			}
			set
			{
				if ((this._P_Name != value))
				{
					this.OnP_NameChanging(value);
					this.SendPropertyChanging();
					this._P_Name = value;
					this.SendPropertyChanged("P_Name");
					this.OnP_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string P_Description
		{
			get
			{
				return this._P_Description;
			}
			set
			{
				if ((this._P_Description != value))
				{
					this.OnP_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._P_Description = value;
					this.SendPropertyChanged("P_Description");
					this.OnP_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Category", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Category
		{
			get
			{
				return this._P_Category;
			}
			set
			{
				if ((this._P_Category != value))
				{
					this.OnP_CategoryChanging(value);
					this.SendPropertyChanging();
					this._P_Category = value;
					this.SendPropertyChanged("P_Category");
					this.OnP_CategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Quantity", DbType="Int NOT NULL")]
		public int P_Quantity
		{
			get
			{
				return this._P_Quantity;
			}
			set
			{
				if ((this._P_Quantity != value))
				{
					this.OnP_QuantityChanging(value);
					this.SendPropertyChanging();
					this._P_Quantity = value;
					this.SendPropertyChanged("P_Quantity");
					this.OnP_QuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Price", DbType="Money NOT NULL")]
		public decimal P_Price
		{
			get
			{
				return this._P_Price;
			}
			set
			{
				if ((this._P_Price != value))
				{
					this.OnP_PriceChanging(value);
					this.SendPropertyChanging();
					this._P_Price = value;
					this.SendPropertyChanged("P_Price");
					this.OnP_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_DateCreated", DbType="Date NOT NULL")]
		public System.DateTime P_DateCreated
		{
			get
			{
				return this._P_DateCreated;
			}
			set
			{
				if ((this._P_DateCreated != value))
				{
					this.OnP_DateCreatedChanging(value);
					this.SendPropertyChanging();
					this._P_DateCreated = value;
					this.SendPropertyChanged("P_DateCreated");
					this.OnP_DateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Image", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Image
		{
			get
			{
				return this._P_Image;
			}
			set
			{
				if ((this._P_Image != value))
				{
					this.OnP_ImageChanging(value);
					this.SendPropertyChanging();
					this._P_Image = value;
					this.SendPropertyChanged("P_Image");
					this.OnP_ImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit NOT NULL")]
		public bool isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Table")]
	public partial class User_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Id;
		
		private string _Email;
		
		private string _Password;
		
		private int _UserType;
		
		private string _Name;
		
		private string _Surname;
		
		private string _Phone_Number;
		
		private string _Address;
		
		private System.DateTime _Register_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdChanging(int value);
    partial void OnUser_IdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserTypeChanging(int value);
    partial void OnUserTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnPhone_NumberChanging(string value);
    partial void OnPhone_NumberChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnRegister_DateChanging(System.DateTime value);
    partial void OnRegister_DateChanged();
    #endregion
		
		public User_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="Int NOT NULL")]
		public int UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_Number", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this.OnPhone_NumberChanging(value);
					this.SendPropertyChanging();
					this._Phone_Number = value;
					this.SendPropertyChanged("Phone_Number");
					this.OnPhone_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Register_Date", DbType="Date NOT NULL")]
		public System.DateTime Register_Date
		{
			get
			{
				return this._Register_Date;
			}
			set
			{
				if ((this._Register_Date != value))
				{
					this.OnRegister_DateChanging(value);
					this.SendPropertyChanging();
					this._Register_Date = value;
					this.SendPropertyChanged("Register_Date");
					this.OnRegister_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
