<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.optiongroups" Member="optiongroups">
    <Type Name="optiongroup">
      <Column Name="optoiongroupid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="optiongroupname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="optiongroup_option" Member="options" ThisKey="optoiongroupid" OtherKey="optiongroupid" Type="option" />
    </Type>
  </Table>
  <Table Name="dbo.options" Member="options">
    <Type Name="option">
      <Column Name="optionid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="optiongroupid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="optionname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="option_productoption" Member="productoptions" ThisKey="optionid" OtherKey="optionid" Type="productoption" />
      <Association Name="optiongroup_option" Member="optiongroup" ThisKey="optiongroupid" OtherKey="optoiongroupid" Type="optiongroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orders" Member="orders">
    <Type Name="order">
      <Column Name="orderid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orderuserid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orderamount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ordershipname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ordershipaddress" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ordershipaddress2" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ordercity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="orderstate" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="orderzip" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ordercountry" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="orderphone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="orderfax" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ordershipping" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ordertax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="orderemail" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ordershipped" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ordertrackingnumber" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Association Name="user_order" Member="user" ThisKey="orderuserid" OtherKey="userid" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.productcatogeries" Member="productcatogeries">
    <Type Name="productcatogery">
      <Column Name="categoryid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categoryname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="productcatogery_product" Member="products" ThisKey="categoryid" OtherKey="productcategoryid" Type="product" />
    </Type>
  </Table>
  <Table Name="dbo.productoptions" Member="productoptions">
    <Type Name="productoption">
      <Column Name="productoptionid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="optionid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="optionpriceincrement" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="option_productoption" Member="option" ThisKey="optionid" OtherKey="optionid" Type="option" IsForeignKey="true" />
      <Association Name="product_productoption" Member="product" ThisKey="productid" OtherKey="productid" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.products" Member="products">
    <Type Name="product">
      <Column Name="productid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productsku" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="productname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="productprice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="productweight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="productcartdesc" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="productshortdesc" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="productlongdesc" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="productthumb" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="productimage" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="productcategoryid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="productstock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="productlive" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="productunlimited" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="productlocation" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="product_productoption" Member="productoptions" ThisKey="productid" OtherKey="productid" Type="productoption" />
      <Association Name="productcatogery_product" Member="productcatogery" ThisKey="productcategoryid" OtherKey="categoryid" Type="productcatogery" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="useremail" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="userpassword" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="userfirstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userlastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usercity" Type="System.String" DbType="VarChar(90) NOT NULL" CanBeNull="false" />
      <Column Name="userstate" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="userzip" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="useremailverified" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="userverificationcode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="userip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="userphone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="userfax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="usercountry" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="useraddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="useraddress2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="user_order" Member="orders" ThisKey="userid" OtherKey="orderuserid" Type="order" />
    </Type>
  </Table>
</Database>