//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.BackendReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User_Table", Namespace="http://schemas.datacontract.org/2004/07/BabyHaven_Database")]
    [System.SerializableAttribute()]
    public partial class User_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Register_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone_Number {
            get {
                return this.Phone_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Phone_NumberField, value) != true)) {
                    this.Phone_NumberField = value;
                    this.RaisePropertyChanged("Phone_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Register_Date {
            get {
                return this.Register_DateField;
            }
            set {
                if ((this.Register_DateField.Equals(value) != true)) {
                    this.Register_DateField = value;
                    this.RaisePropertyChanged("Register_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/BabyHaven_Database")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int U_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int U_Id {
            get {
                return this.U_IdField;
            }
            set {
                if ((this.U_IdField.Equals(value) != true)) {
                    this.U_IdField = value;
                    this.RaisePropertyChanged("U_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/BabyHaven_Database")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int U_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int U_Id {
            get {
                return this.U_IdField;
            }
            set {
                if ((this.U_IdField.Equals(value) != true)) {
                    this.U_IdField = value;
                    this.RaisePropertyChanged("U_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/BabyHaven_Database")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Cart_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cart_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int P_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int U_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cart_Price {
            get {
                return this.Cart_PriceField;
            }
            set {
                if ((this.Cart_PriceField.Equals(value) != true)) {
                    this.Cart_PriceField = value;
                    this.RaisePropertyChanged("Cart_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cart_Quantity {
            get {
                return this.Cart_QuantityField;
            }
            set {
                if ((this.Cart_QuantityField.Equals(value) != true)) {
                    this.Cart_QuantityField = value;
                    this.RaisePropertyChanged("Cart_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int P_Id {
            get {
                return this.P_IdField;
            }
            set {
                if ((this.P_IdField.Equals(value) != true)) {
                    this.P_IdField = value;
                    this.RaisePropertyChanged("P_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int U_Id {
            get {
                return this.U_IdField;
            }
            set {
                if ((this.U_IdField.Equals(value) != true)) {
                    this.U_IdField = value;
                    this.RaisePropertyChanged("U_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/BabyHaven_Database")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime P_DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal P_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int P_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Category {
            get {
                return this.P_CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.P_CategoryField, value) != true)) {
                    this.P_CategoryField = value;
                    this.RaisePropertyChanged("P_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime P_DateCreated {
            get {
                return this.P_DateCreatedField;
            }
            set {
                if ((this.P_DateCreatedField.Equals(value) != true)) {
                    this.P_DateCreatedField = value;
                    this.RaisePropertyChanged("P_DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Description {
            get {
                return this.P_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.P_DescriptionField, value) != true)) {
                    this.P_DescriptionField = value;
                    this.RaisePropertyChanged("P_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Image {
            get {
                return this.P_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.P_ImageField, value) != true)) {
                    this.P_ImageField = value;
                    this.RaisePropertyChanged("P_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_Name {
            get {
                return this.P_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.P_NameField, value) != true)) {
                    this.P_NameField = value;
                    this.RaisePropertyChanged("P_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal P_Price {
            get {
                return this.P_PriceField;
            }
            set {
                if ((this.P_PriceField.Equals(value) != true)) {
                    this.P_PriceField = value;
                    this.RaisePropertyChanged("P_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int P_Quantity {
            get {
                return this.P_QuantityField;
            }
            set {
                if ((this.P_QuantityField.Equals(value) != true)) {
                    this.P_QuantityField = value;
                    this.RaisePropertyChanged("P_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_Id {
            get {
                return this.Product_IdField;
            }
            set {
                if ((this.Product_IdField.Equals(value) != true)) {
                    this.Product_IdField = value;
                    this.RaisePropertyChanged("Product_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackendReference.IBabyHavenService")]
    public interface IBabyHavenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/Login", ReplyAction="http://tempuri.org/IBabyHavenService/LoginResponse")]
        int Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/Login", ReplyAction="http://tempuri.org/IBabyHavenService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetUser", ReplyAction="http://tempuri.org/IBabyHavenService/GetUserResponse")]
        Frontend.BackendReference.User_Table GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetUser", ReplyAction="http://tempuri.org/IBabyHavenService/GetUserResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.User_Table> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetEmail", ReplyAction="http://tempuri.org/IBabyHavenService/GetEmailResponse")]
        Frontend.BackendReference.User_Table GetEmail(string email, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetEmail", ReplyAction="http://tempuri.org/IBabyHavenService/GetEmailResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.User_Table> GetEmailAsync(string email, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetAdmin", ReplyAction="http://tempuri.org/IBabyHavenService/GetAdminResponse")]
        Frontend.BackendReference.Admin GetAdmin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetAdmin", ReplyAction="http://tempuri.org/IBabyHavenService/GetAdminResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.Admin> GetAdminAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetClient", ReplyAction="http://tempuri.org/IBabyHavenService/GetClientResponse")]
        Frontend.BackendReference.Client GetClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetClient", ReplyAction="http://tempuri.org/IBabyHavenService/GetClientResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.Client> GetClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetAllUsers", ReplyAction="http://tempuri.org/IBabyHavenService/GetAllUsersResponse")]
        Frontend.BackendReference.User_Table[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetAllUsers", ReplyAction="http://tempuri.org/IBabyHavenService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.User_Table[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/Register", ReplyAction="http://tempuri.org/IBabyHavenService/RegisterResponse")]
        bool Register(string email, string password, string name, string surname, string phoneno, string address, int usetype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/Register", ReplyAction="http://tempuri.org/IBabyHavenService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string email, string password, string name, string surname, string phoneno, string address, int usetype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/AddAdmin", ReplyAction="http://tempuri.org/IBabyHavenService/AddAdminResponse")]
        bool AddAdmin(int user, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/AddAdmin", ReplyAction="http://tempuri.org/IBabyHavenService/AddAdminResponse")]
        System.Threading.Tasks.Task<bool> AddAdminAsync(int user, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/SearchUsersByName", ReplyAction="http://tempuri.org/IBabyHavenService/SearchUsersByNameResponse")]
        Frontend.BackendReference.User_Table[] SearchUsersByName(string searchQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/SearchUsersByName", ReplyAction="http://tempuri.org/IBabyHavenService/SearchUsersByNameResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.User_Table[]> SearchUsersByNameAsync(string searchQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/AddToCart", ReplyAction="http://tempuri.org/IBabyHavenService/AddToCartResponse")]
        bool AddToCart(int uId, int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/AddToCart", ReplyAction="http://tempuri.org/IBabyHavenService/AddToCartResponse")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(int uId, int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetTotalCartPrice", ReplyAction="http://tempuri.org/IBabyHavenService/GetTotalCartPriceResponse")]
        decimal GetTotalCartPrice(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetTotalCartPrice", ReplyAction="http://tempuri.org/IBabyHavenService/GetTotalCartPriceResponse")]
        System.Threading.Tasks.Task<decimal> GetTotalCartPriceAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetAllCartItemsForClient", ReplyAction="http://tempuri.org/IBabyHavenService/GetAllCartItemsForClientResponse")]
        Frontend.BackendReference.Cart[] GetAllCartItemsForClient(int ClientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetAllCartItemsForClient", ReplyAction="http://tempuri.org/IBabyHavenService/GetAllCartItemsForClientResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.Cart[]> GetAllCartItemsForClientAsync(int ClientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetCartProducts", ReplyAction="http://tempuri.org/IBabyHavenService/GetCartProductsResponse")]
        Frontend.BackendReference.Product[] GetCartProducts(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetCartProducts", ReplyAction="http://tempuri.org/IBabyHavenService/GetCartProductsResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.Product[]> GetCartProductsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetQuantity", ReplyAction="http://tempuri.org/IBabyHavenService/GetQuantityResponse")]
        int GetQuantity(int UserID, int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetQuantity", ReplyAction="http://tempuri.org/IBabyHavenService/GetQuantityResponse")]
        System.Threading.Tasks.Task<int> GetQuantityAsync(int UserID, int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/AddRemoveProductFromCart", ReplyAction="http://tempuri.org/IBabyHavenService/AddRemoveProductFromCartResponse")]
        void AddRemoveProductFromCart(int pID, int uID, string action, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/AddRemoveProductFromCart", ReplyAction="http://tempuri.org/IBabyHavenService/AddRemoveProductFromCartResponse")]
        System.Threading.Tasks.Task AddRemoveProductFromCartAsync(int pID, int uID, string action, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/RemoveProductFromCart", ReplyAction="http://tempuri.org/IBabyHavenService/RemoveProductFromCartResponse")]
        void RemoveProductFromCart(int productId, int userId, int quantityToRemove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/RemoveProductFromCart", ReplyAction="http://tempuri.org/IBabyHavenService/RemoveProductFromCartResponse")]
        System.Threading.Tasks.Task RemoveProductFromCartAsync(int productId, int userId, int quantityToRemove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetProductImage", ReplyAction="http://tempuri.org/IBabyHavenService/GetProductImageResponse")]
        string GetProductImage(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetProductImage", ReplyAction="http://tempuri.org/IBabyHavenService/GetProductImageResponse")]
        System.Threading.Tasks.Task<string> GetProductImageAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetProductName", ReplyAction="http://tempuri.org/IBabyHavenService/GetProductNameResponse")]
        string GetProductName(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetProductName", ReplyAction="http://tempuri.org/IBabyHavenService/GetProductNameResponse")]
        System.Threading.Tasks.Task<string> GetProductNameAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetProductPrice", ReplyAction="http://tempuri.org/IBabyHavenService/GetProductPriceResponse")]
        decimal GetProductPrice(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/GetProductPrice", ReplyAction="http://tempuri.org/IBabyHavenService/GetProductPriceResponse")]
        System.Threading.Tasks.Task<decimal> GetProductPriceAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/Getallproducts", ReplyAction="http://tempuri.org/IBabyHavenService/GetallproductsResponse")]
        Frontend.BackendReference.Product[] Getallproducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/Getallproducts", ReplyAction="http://tempuri.org/IBabyHavenService/GetallproductsResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.Product[]> GetallproductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/getProductCat", ReplyAction="http://tempuri.org/IBabyHavenService/getProductCatResponse")]
        Frontend.BackendReference.Product[] getProductCat(string cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/getProductCat", ReplyAction="http://tempuri.org/IBabyHavenService/getProductCatResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.Product[]> getProductCatAsync(string cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/getSingleProd", ReplyAction="http://tempuri.org/IBabyHavenService/getSingleProdResponse")]
        Frontend.BackendReference.Product getSingleProd(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/getSingleProd", ReplyAction="http://tempuri.org/IBabyHavenService/getSingleProdResponse")]
        System.Threading.Tasks.Task<Frontend.BackendReference.Product> getSingleProdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/Addproducts", ReplyAction="http://tempuri.org/IBabyHavenService/AddproductsResponse")]
        string Addproducts(string name, string description, string cat, int quantity, decimal price, bool active, int prodID, int admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/Addproducts", ReplyAction="http://tempuri.org/IBabyHavenService/AddproductsResponse")]
        System.Threading.Tasks.Task<string> AddproductsAsync(string name, string description, string cat, int quantity, decimal price, bool active, int prodID, int admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/numDifferentProductsSold", ReplyAction="http://tempuri.org/IBabyHavenService/numDifferentProductsSoldResponse")]
        int numDifferentProductsSold();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/numDifferentProductsSold", ReplyAction="http://tempuri.org/IBabyHavenService/numDifferentProductsSoldResponse")]
        System.Threading.Tasks.Task<int> numDifferentProductsSoldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/numOnHand", ReplyAction="http://tempuri.org/IBabyHavenService/numOnHandResponse")]
        int numOnHand(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/numOnHand", ReplyAction="http://tempuri.org/IBabyHavenService/numOnHandResponse")]
        System.Threading.Tasks.Task<int> numOnHandAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/regperday", ReplyAction="http://tempuri.org/IBabyHavenService/regperdayResponse")]
        int regperday();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyHavenService/regperday", ReplyAction="http://tempuri.org/IBabyHavenService/regperdayResponse")]
        System.Threading.Tasks.Task<int> regperdayAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBabyHavenServiceChannel : Frontend.BackendReference.IBabyHavenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BabyHavenServiceClient : System.ServiceModel.ClientBase<Frontend.BackendReference.IBabyHavenService>, Frontend.BackendReference.IBabyHavenService {
        
        public BabyHavenServiceClient() {
        }
        
        public BabyHavenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BabyHavenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BabyHavenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BabyHavenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public Frontend.BackendReference.User_Table GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.User_Table> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public Frontend.BackendReference.User_Table GetEmail(string email, int id) {
            return base.Channel.GetEmail(email, id);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.User_Table> GetEmailAsync(string email, int id) {
            return base.Channel.GetEmailAsync(email, id);
        }
        
        public Frontend.BackendReference.Admin GetAdmin(int id) {
            return base.Channel.GetAdmin(id);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.Admin> GetAdminAsync(int id) {
            return base.Channel.GetAdminAsync(id);
        }
        
        public Frontend.BackendReference.Client GetClient(int id) {
            return base.Channel.GetClient(id);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.Client> GetClientAsync(int id) {
            return base.Channel.GetClientAsync(id);
        }
        
        public Frontend.BackendReference.User_Table[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.User_Table[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public bool Register(string email, string password, string name, string surname, string phoneno, string address, int usetype) {
            return base.Channel.Register(email, password, name, surname, phoneno, address, usetype);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string email, string password, string name, string surname, string phoneno, string address, int usetype) {
            return base.Channel.RegisterAsync(email, password, name, surname, phoneno, address, usetype);
        }
        
        public bool AddAdmin(int user, string surname) {
            return base.Channel.AddAdmin(user, surname);
        }
        
        public System.Threading.Tasks.Task<bool> AddAdminAsync(int user, string surname) {
            return base.Channel.AddAdminAsync(user, surname);
        }
        
        public Frontend.BackendReference.User_Table[] SearchUsersByName(string searchQuery) {
            return base.Channel.SearchUsersByName(searchQuery);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.User_Table[]> SearchUsersByNameAsync(string searchQuery) {
            return base.Channel.SearchUsersByNameAsync(searchQuery);
        }
        
        public bool AddToCart(int uId, int pId) {
            return base.Channel.AddToCart(uId, pId);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(int uId, int pId) {
            return base.Channel.AddToCartAsync(uId, pId);
        }
        
        public decimal GetTotalCartPrice(int clientId) {
            return base.Channel.GetTotalCartPrice(clientId);
        }
        
        public System.Threading.Tasks.Task<decimal> GetTotalCartPriceAsync(int clientId) {
            return base.Channel.GetTotalCartPriceAsync(clientId);
        }
        
        public Frontend.BackendReference.Cart[] GetAllCartItemsForClient(int ClientID) {
            return base.Channel.GetAllCartItemsForClient(ClientID);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.Cart[]> GetAllCartItemsForClientAsync(int ClientID) {
            return base.Channel.GetAllCartItemsForClientAsync(ClientID);
        }
        
        public Frontend.BackendReference.Product[] GetCartProducts(int id) {
            return base.Channel.GetCartProducts(id);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.Product[]> GetCartProductsAsync(int id) {
            return base.Channel.GetCartProductsAsync(id);
        }
        
        public int GetQuantity(int UserID, int ProductID) {
            return base.Channel.GetQuantity(UserID, ProductID);
        }
        
        public System.Threading.Tasks.Task<int> GetQuantityAsync(int UserID, int ProductID) {
            return base.Channel.GetQuantityAsync(UserID, ProductID);
        }
        
        public void AddRemoveProductFromCart(int pID, int uID, string action, int amount) {
            base.Channel.AddRemoveProductFromCart(pID, uID, action, amount);
        }
        
        public System.Threading.Tasks.Task AddRemoveProductFromCartAsync(int pID, int uID, string action, int amount) {
            return base.Channel.AddRemoveProductFromCartAsync(pID, uID, action, amount);
        }
        
        public void RemoveProductFromCart(int productId, int userId, int quantityToRemove) {
            base.Channel.RemoveProductFromCart(productId, userId, quantityToRemove);
        }
        
        public System.Threading.Tasks.Task RemoveProductFromCartAsync(int productId, int userId, int quantityToRemove) {
            return base.Channel.RemoveProductFromCartAsync(productId, userId, quantityToRemove);
        }
        
        public string GetProductImage(int productID) {
            return base.Channel.GetProductImage(productID);
        }
        
        public System.Threading.Tasks.Task<string> GetProductImageAsync(int productID) {
            return base.Channel.GetProductImageAsync(productID);
        }
        
        public string GetProductName(int productID) {
            return base.Channel.GetProductName(productID);
        }
        
        public System.Threading.Tasks.Task<string> GetProductNameAsync(int productID) {
            return base.Channel.GetProductNameAsync(productID);
        }
        
        public decimal GetProductPrice(int productID) {
            return base.Channel.GetProductPrice(productID);
        }
        
        public System.Threading.Tasks.Task<decimal> GetProductPriceAsync(int productID) {
            return base.Channel.GetProductPriceAsync(productID);
        }
        
        public Frontend.BackendReference.Product[] Getallproducts() {
            return base.Channel.Getallproducts();
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.Product[]> GetallproductsAsync() {
            return base.Channel.GetallproductsAsync();
        }
        
        public Frontend.BackendReference.Product[] getProductCat(string cat) {
            return base.Channel.getProductCat(cat);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.Product[]> getProductCatAsync(string cat) {
            return base.Channel.getProductCatAsync(cat);
        }
        
        public Frontend.BackendReference.Product getSingleProd(int id) {
            return base.Channel.getSingleProd(id);
        }
        
        public System.Threading.Tasks.Task<Frontend.BackendReference.Product> getSingleProdAsync(int id) {
            return base.Channel.getSingleProdAsync(id);
        }
        
        public string Addproducts(string name, string description, string cat, int quantity, decimal price, bool active, int prodID, int admin) {
            return base.Channel.Addproducts(name, description, cat, quantity, price, active, prodID, admin);
        }
        
        public System.Threading.Tasks.Task<string> AddproductsAsync(string name, string description, string cat, int quantity, decimal price, bool active, int prodID, int admin) {
            return base.Channel.AddproductsAsync(name, description, cat, quantity, price, active, prodID, admin);
        }
        
        public int numDifferentProductsSold() {
            return base.Channel.numDifferentProductsSold();
        }
        
        public System.Threading.Tasks.Task<int> numDifferentProductsSoldAsync() {
            return base.Channel.numDifferentProductsSoldAsync();
        }
        
        public int numOnHand(int id) {
            return base.Channel.numOnHand(id);
        }
        
        public System.Threading.Tasks.Task<int> numOnHandAsync(int id) {
            return base.Channel.numOnHandAsync(id);
        }
        
        public int regperday() {
            return base.Channel.regperday();
        }
        
        public System.Threading.Tasks.Task<int> regperdayAsync() {
            return base.Channel.regperdayAsync();
        }
    }
}
